development: &default

  # Credentials for REST APIs
  client_id: AX3vCRA-vTG7Ja7GnHJl0eEbZg-MbW5OYD_sWrquOp2BKeaDZomRVJuSuCV_
  client_secret: EESJPxBaiebhv9q-dCQdLv_rn9wfoQ5VBAAs2-r7jEpxs1eNpmAlzS9r1iQS

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: k.ashok502-facilitator_api1.gmail.com
  password: 1366968794
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AwVzeB7ThvogKHzICFAE2dVcZPjR
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: k.ashok502@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

test:
  <<: *default

production:
  <<: *default
  mode: sandbox
